INFO  2018-02-25 13:59:18,509 (Saros.java:220) Starting Saros 14.10.31 running:
  Java Version: 1.8.0_161
  Java Vendor: Oracle Corporation
  Eclipse Runtime Version: 3.12.0.v20160606-1342
  Operating System: Windows 10 (10.0)
  Hardware Architecture: amd64
INFO  2018-02-25 13:59:18,528 (SarosContext.java:153) creating Saros runtime context...
INFO  2018-02-25 13:59:18,680 (SarosContext.java:199) successfully created Saros runtime context
DEBUG 2018-02-25 13:59:18,696 (DataTransferManager.java:467) used transport order for the current XMPP connection: [XMPP-Socks5-Transport, XMPP-IBB-Transport]
INFO  2018-02-25 13:59:18,717 (PreferenceInitializer.java:50) initializing preference default values
DEBUG 2018-02-25 13:59:18,753 (SarosAnnotation.java:117) resetting annotation colors
DEBUG 2018-02-25 13:59:18,757 (Saros.java:264) autogenerated favorite color id is: 1
INFO  2018-02-25 13:59:18,768 (XMPPAccountStore.java:106) loaded 0 accounts
DEBUG 2018-02-25 13:59:20,953 (SharedDocumentProvider.java:77) SharedDocumentProvider created by Eclipse
DEBUG 2018-02-25 13:59:22,354 (WhiteboardManager.java:194) WhiteboardManager instantiated
DEBUG 2018-02-25 13:59:22,363 (DocumentRecord.java:93) Added Node: attr(151959236236188530) name=svg
DEBUG 2018-02-26 17:41:11,189 (XMPPAccountStore.java:232) saved 1 account(s)
DEBUG 2018-02-26 17:41:11,270 (XMPPConnectionService.java:439) started Socks5 proxy on port: 7777 [listening on all interfaces]
DEBUG 2018-02-26 17:41:11,311 (XMPPConnectionService.java:459) using autodetected addresses: [10.96.65.144, fe80:0:0:0:adb3:446b:3258:caff%eth0, 2001:0:4137:9e76:3062:86a0:649d:7cff, fe80:0:0:0:3062:86a0:649d:7cff%net3]
DEBUG 2018-02-26 17:41:11,316 (XMPPConnectionService.java:398)  new connection state == CONNECTING
WARN  2018-02-26 17:41:21,509 (StunServiceImpl.java:420) received no response from STUN server stunserver.org/67.227.226.240:3478 at local address /10.96.65.144:0
ERROR 2018-02-26 17:41:32,326 (XMPPConnectionService.java:400)  new connection state == ERROR
gmail.com:5222 Exception: XMPPError connecting to gmail.com:5222.; : remote-server-error(502)
  -- caused by: XMPPError connecting to gmail.com:5222.: remote-server-error(502) XMPPError connecting to gmail.com:5222.
  -- caused by: java.net.ConnectException: Connection timed out: connect
	at org.jivesoftware.smack.XMPPConnection.connectUsingConfiguration(XMPPConnection.java:592)
	at org.jivesoftware.smack.XMPPConnection.connect(XMPPConnection.java:1010)
	at de.fu_berlin.inf.dpp.net.xmpp.XMPPConnectionService.connect(XMPPConnectionService.java:268)
	at de.fu_berlin.inf.dpp.communication.connection.ConnectionHandler.connectXMPPInternal(ConnectionHandler.java:332)
	at de.fu_berlin.inf.dpp.communication.connection.ConnectionHandler.connect(ConnectionHandler.java:190)
	at de.fu_berlin.inf.dpp.ui.wizards.AddXMPPAccountWizard$1.run(AddXMPPAccountWizard.java:125)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.lang.Thread.run(Unknown Source)
Nested Exception: 
XMPPError connecting to gmail.com:5222.: remote-server-error(502) XMPPError connecting to gmail.com:5222.
  -- caused by: java.net.ConnectException: Connection timed out: connect
	at org.jivesoftware.smack.XMPPConnection.connectUsingConfiguration(XMPPConnection.java:565)
	at org.jivesoftware.smack.XMPPConnection.connect(XMPPConnection.java:1010)
	at de.fu_berlin.inf.dpp.net.xmpp.XMPPConnectionService.connect(XMPPConnectionService.java:268)
	at de.fu_berlin.inf.dpp.communication.connection.ConnectionHandler.connectXMPPInternal(ConnectionHandler.java:332)
	at de.fu_berlin.inf.dpp.communication.connection.ConnectionHandler.connect(ConnectionHandler.java:190)
	at de.fu_berlin.inf.dpp.ui.wizards.AddXMPPAccountWizard$1.run(AddXMPPAccountWizard.java:125)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.lang.Thread.run(Unknown Source)
Nested Exception: 
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.jivesoftware.smack.proxy.DirectSocketFactory.createSocket(DirectSocketFactory.java:45)
	at org.jivesoftware.smack.XMPPConnection.connectUsingConfiguration(XMPPConnection.java:557)
	at org.jivesoftware.smack.XMPPConnection.connect(XMPPConnection.java:1010)
	at de.fu_berlin.inf.dpp.net.xmpp.XMPPConnectionService.connect(XMPPConnectionService.java:268)
	at de.fu_berlin.inf.dpp.communication.connection.ConnectionHandler.connectXMPPInternal(ConnectionHandler.java:332)
	at de.fu_berlin.inf.dpp.communication.connection.ConnectionHandler.connect(ConnectionHandler.java:190)
	at de.fu_berlin.inf.dpp.ui.wizards.AddXMPPAccountWizard$1.run(AddXMPPAccountWizard.java:125)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.lang.Thread.run(Unknown Source)
DEBUG 2018-02-26 17:41:32,336 (XMPPConnectionService.java:398)  new connection state == NOT_CONNECTED
DEBUG 2018-02-26 17:41:53,630 (XMPPAccountStore.java:232) saved 1 account(s)
DEBUG 2018-02-26 17:41:53,832 (XMPPConnectionService.java:439) started Socks5 proxy on port: 7777 [listening on all interfaces]
DEBUG 2018-02-26 17:41:53,867 (XMPPConnectionService.java:459) using autodetected addresses: [10.96.65.144, fe80:0:0:0:adb3:446b:3258:caff%eth0, 2001:0:4137:9e76:3062:86a0:649d:7cff, fe80:0:0:0:3062:86a0:649d:7cff%net3]
DEBUG 2018-02-26 17:41:53,867 (XMPPConnectionService.java:398)  new connection state == CONNECTING
DEBUG 2018-02-26 17:41:54,705 (XMPPConnectionService.java:398) pabstaaron@gmail.com/Saros02AA75B5 new connection state == CONNECTED
DEBUG 2018-02-26 17:41:54,705 (DataTransferManager.java:467) used transport order for the current XMPP connection: [XMPP-Socks5-Transport, XMPP-IBB-Transport]
DEBUG 2018-02-26 17:41:54,709 (SkypeManager.java:289) Refreshing Skype username cache...
WARN  2018-02-26 17:42:03,905 (StunServiceImpl.java:420) received no response from STUN server stunserver.org/67.227.226.240:3478 at local address /10.96.65.144:0
WARN  2018-02-26 17:42:24,915 (DiscoveryManager.java:451) Service Discovery failed on recipient nathan.donaldsondrum@gmail.com/MessagingADF5D2EC059 server: xmpp.l.google.com
No response from the server.: 
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:534)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:489)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.performServiceDiscovery(DiscoveryManager.java:448)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.queryFeatureSupport(DiscoveryManager.java:380)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.access$3(DiscoveryManager.java:347)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager$2.run(DiscoveryManager.java:326)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
WARN  2018-02-26 17:42:54,925 (DiscoveryManager.java:451) Service Discovery failed on recipient bnagel25@gmail.com/MessagingAfc3ae4f9 server: xmpp.l.google.com
No response from the server.: 
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:534)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:489)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.performServiceDiscovery(DiscoveryManager.java:448)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.queryFeatureSupport(DiscoveryManager.java:380)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.access$3(DiscoveryManager.java:347)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager$2.run(DiscoveryManager.java:326)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
WARN  2018-02-26 17:56:46,680 (DiscoveryManager.java:451) Service Discovery failed on recipient bnagel25@gmail.com/MessagingAfc3ae4f9 server: xmpp.l.google.com
No response from the server.: 
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:534)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:489)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.performServiceDiscovery(DiscoveryManager.java:448)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.queryFeatureSupport(DiscoveryManager.java:380)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.access$3(DiscoveryManager.java:347)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager$2.run(DiscoveryManager.java:326)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
WARN  2018-02-26 17:47:59,623 (DiscoveryManager.java:451) Service Discovery failed on recipient bnagel25@gmail.com/messaging-lcsw_hangouts_BB33F419 server: xmpp.l.google.com
No response from the server.: 
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:534)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:489)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.performServiceDiscovery(DiscoveryManager.java:448)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.queryFeatureSupport(DiscoveryManager.java:380)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.access$3(DiscoveryManager.java:347)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager$2.run(DiscoveryManager.java:326)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
WARN  2018-02-26 17:48:29,659 (DiscoveryManager.java:451) Service Discovery failed on recipient bnagel25@gmail.com/messaging-lcsw_hangouts_BB33F419 server: xmpp.l.google.com
No response from the server.: 
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:534)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:489)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.performServiceDiscovery(DiscoveryManager.java:448)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.queryFeatureSupport(DiscoveryManager.java:380)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.access$3(DiscoveryManager.java:347)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager$2.run(DiscoveryManager.java:326)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
DEBUG 2018-02-26 18:01:53,444 (DiscoveryManager.java:101) clearing cache entry of contact bnagel25@gmail.com/messaging-lcsw_hangouts_BB33F419 but cache entry is empty (a discovery is still running or the last one failed)
WARN  2018-02-26 18:01:53,559 (DiscoveryManager.java:451) Service Discovery failed on recipient bnagel25@gmail.com/messaging-lcsw_hangouts_BB33F419 server: xmpp.l.google.com
service-unavailable(503)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:537)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:489)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.performServiceDiscovery(DiscoveryManager.java:448)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.queryFeatureSupport(DiscoveryManager.java:380)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.access$3(DiscoveryManager.java:347)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager$2.run(DiscoveryManager.java:326)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
DEBUG 2018-02-26 17:55:37,757 (DiscoveryManager.java:101) clearing cache entry of contact bnagel25@gmail.com/MessagingAfc3ae4f9 but cache entry is empty (a discovery is still running or the last one failed)
DEBUG 2018-02-26 17:55:37,761 (DiscoveryManager.java:101) clearing cache entry of contact nathan.donaldsondrum@gmail.com/MessagingADF5D2EC059 but cache entry is empty (a discovery is still running or the last one failed)
ERROR 2018-02-26 17:55:37,762 (XMPPConnectionService.java:101) XMPP connection error: 
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.read1(Unknown Source)
	at java.io.BufferedReader.read(Unknown Source)
	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:2992)
	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1144)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at org.jivesoftware.smack.PacketReader.parsePackets(PacketReader.java:312)
	at org.jivesoftware.smack.PacketReader.access$000(PacketReader.java:48)
	at org.jivesoftware.smack.PacketReader$1.run(PacketReader.java:76)
ERROR 2018-02-26 17:55:37,796 (XMPPConnectionService.java:400)  new connection state == ERROR
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.read1(Unknown Source)
	at java.io.BufferedReader.read(Unknown Source)
	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:2992)
	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1144)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at org.jivesoftware.smack.PacketReader.parsePackets(PacketReader.java:312)
	at org.jivesoftware.smack.PacketReader.access$000(PacketReader.java:48)
	at org.jivesoftware.smack.PacketReader$1.run(PacketReader.java:76)
DEBUG 2018-02-26 17:55:37,805 (XMPPConnectionService.java:398)  new connection state == NOT_CONNECTED
DEBUG 2018-02-26 17:35:52,883 (UPnPServiceImpl.java:295) deleting existing port mappings
